name: Hello GIthub Actions

on: 
    push:
        branches: ["*"]
jobs:
    build:
        runs-on: unbuntu-latest
        steps: 
            - uses: action/checkout@v2
            - uses: actions/setup=node@v1
              with: 
                  node-version: 16
            - run: npm ci
            - run: npm run test
            - run: npm run build
            - run: npm run deploy
